[package]
name = "weak-salt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.4"
log = "0.4.14"
env_logger = "0.9.0"
utils = { path = "../utils" }